--- #YAML:1.0
name:               IPC-ConcurrencyLimit-Lock-NFS
version:            0.01
abstract:           Locking via NFS
author:
    - Steffen Mueller <smueller@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 0
    Fcntl:                0
    File::Path:           0
    File::SharedNFSLock:  0.03
    File::Temp:           0
    IPC::ConcurrencyLimit:  0.01
    IPC::ConcurrencyLimit::Lock:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
